more doxygen changes
NOAA-EMC/UFS_UTILS pull request #209
Opened 2020-11-03 13:51 UTC by edwardhartnett

Part of #191 

Next batch of code files converted to doxygen.

2020-11-04 20:11 UTC, GeorgeGayno-NOAA requested changes
@edwardhartnett, if you check the syntax of pmat.f90, I can merge this next.

2020-11-04 20:35 UTC, edwardhartnett commented on sorc/grid_tools.fd/regional_esg_grid.fd/pmat.f90
> +!> @date
OK, stand by, lots of meetings today!

2020-11-04 21:54 UTC, edwardhartnett commented on sorc/grid_tools.fd/regional_esg_grid.fd/pmat.f90
> +!> @date
OK, fixed.

2020-11-05 21:25 UTC, GeorgeGayno-NOAA approved these changes
Everything looks correct.  Will merge.

2020-11-05 21:27 UTC, GeorgeGayno-NOAA commented
@edwardhartnett Changes look good.  But there is a warning about your branch being out of date with the base branch.  Try another merge from develop.

2020-11-06 13:53 UTC, merged