More doxygen updates
NOAA-EMC/UFS_UTILS pull request #220
Opened 2020-11-12 14:55 UTC by edwardhartnett

Part of #191 

More doxygen updates. More to come. ;-)

2020-11-16 14:05 UTC, edwardhartnett commented
Can we get this merged soon, then I will do the next batch.

2020-11-17 10:56 UTC, edwardhartnett commented
@GeorgeGayno-NOAA can we get these merged soon? Thanks!

2020-11-17 13:11 UTC, GeorgeGayno-NOAA requested changes
> @GeorgeGayno-NOAA can we get these merged soon? Thanks!

@edwardhartnett Did you see my comments?

2020-11-17 14:03 UTC, edwardhartnett commented on sorc/fre-nctools.fd/shared_lib/affinity.c
>  #define _GNU_SOURCE
Sorry, didn't see these comments at first. Good catch, the Doxyfile.in was not including C code! I have fixed and updated the docs online.

2020-11-17 15:33 UTC, GeorgeGayno-NOAA approved these changes
I can now see all files at: https://noaa-emc.github.io/UFS_UTILS/

Ready to merge.

2020-11-17 15:59 UTC, edwardhartnett commented
You do the merges right? So I will wait for you to merge this, then submit the next batch of changes.

2020-11-17 16:07 UTC, GeorgeGayno-NOAA commented
> You do the merges right? So I will wait for you to merge this, then submit the next batch of changes.

Yes.  I will do the merge.

2020-11-17 16:08 UTC, merged