Various bug fixes and code improvements
NOAA-EMC/UFS_UTILS pull request #230
Opened 2020-11-20 19:05 UTC by LarissaReames-NOAA

This PR addresses all of the items listed in Issue #228 . Each item in that issue is addressed with its own commit.

2020-11-23 14:51 UTC, GeorgeGayno-NOAA commented
@LarissaReames-NOAA The authoritative repo was updated this morning.  Merge these changes to your fork.  Then, I will do my final review and merge.

2020-11-23 17:29 UTC, LarissaReames-NOAA commented
> @LarissaReames-NOAA The authoritative repo was updated this morning. Merge these changes to your fork. Then, I will do my final review and merge.

Done.

2020-11-23 20:13 UTC, GeorgeGayno-NOAA commented
I compiled the branch at 840d5a8 on WCOSS-Dell.  All chgres_cube regression tests passed.

2020-11-30 20:55 UTC, LarissaReames-NOAA commented
> I compiled the branch at [840d5a8](https://github.com/NOAA-EMC/UFS_UTILS/commit/840d5a83d6709565c1fb4d4bbab3416928fa01be) on WCOSS-Dell. All chgres_cube regression tests passed.

Anything left to change before merge?

2020-11-30 21:05 UTC, GeorgeGayno-NOAA requested changes
Did you see my comments about the call to the error handler?  Also, 'develop' was updated this morning.  You may need to do a merge

2020-11-30 21:28 UTC, LarissaReames-NOAA commented on sorc/chgres_cube.fd/input_data.F90
> +     if (rc /= nf90_noerr) call error_handler("READING GEOGRID FILE",rc)
No, I was never notified of this comment, but it's been addressed in the latest commit.

2020-12-01 15:01 UTC, GeorgeGayno-NOAA commented
Compiled the branch at 90b1f0d on WCOSS-Dell.  All chgres_cube regression tests passed.  Comments on error handling were addressed.  Will merge.

2020-12-01 15:01 UTC, GeorgeGayno-NOAA approved these changes

2020-12-01 15:08 UTC, merged