Create Doxygen documentation for enclosure_cnvx
NOAA-EMC/UFS_UTILS pull request #376
Opened 2021-03-02 15:28 UTC by kgerheiser

Fixes #313 

@GeorgeGayno-NOAA what is `co_gc`?

2021-03-02 15:29 UTC, edwardhartnett commented
Please also include the name of the utility in PR titles.

2021-03-02 15:32 UTC, edwardhartnett requested changes

2021-03-02 15:32 UTC, edwardhartnett commented on sorc/orog_mask_tools.fd/lake.fd/enclosure_cnvx.F90
> +!> Test whether a given point, p, is inside a convex spherical polygon defined with a series of n vertices
Add @author and @brief tags at the file leve.

I see there is some test code here. In such cases create an issue titled something like: "recover test code in orog_mask_tools.fd/lake.fd/enclosure_cnvx.F90 as unit test"

2021-03-02 15:32 UTC, edwardhartnett commented on sorc/orog_mask_tools.fd/lake.fd/enclosure_cnvx.F90
> +!! Both the test point and the polygon are specified in latitude and longitude radians
Punctuation at the end of all sentences please. (Why is this missing from so much of our fortran documentation? Did we used to charge extra for programmers to use the '.' key?)

2021-03-02 16:17 UTC, edwardhartnett approved these changes

2021-03-03 12:32 UTC, edwardhartnett commented
@GeorgeGayno-NOAA can you answer Kyle's question so we can get this merged?

2021-03-03 14:22 UTC, GeorgeGayno-NOAA commented
> Fixes #313
> 
> @GeorgeGayno-NOAA what is `co_gc`?

Let me take a look.

2021-03-03 14:31 UTC, GeorgeGayno-NOAA commented
@shansun6 Can you define the variable co_gc for us?

2021-03-03 22:16 UTC, GeorgeGayno-NOAA commented
Here is the definition of 'co_gc' from Ning Wang:

```
The following is the definition of co_gc:

co_gc, integer
  = i: if test point is on or within the distance of epsilon (0.000000000000001D0 currently) to side i of the given 
spherical polygon ;
  = 0: if test point is not on any side of the given spherical polygon.

*It is assumed that a side of a spherical polygon is a great-circle arc that connects 2 adjacent vertices of the polygon.

The output variable co_gc from enclosure_cnvx( ) is not being used by lakefrac program, which only needs to know 
if a test point is inside a given spherical quadrilateral.
```

2021-03-04 14:43 UTC, edwardhartnett commented
Kyle if you can insert George's answer into the documentation somewhere, we can get this merged.

2021-03-04 15:13 UTC, edwardhartnett approved these changes

2021-03-04 15:14 UTC, merged