chgres_cube: Add a check at static data read for incompatible old static data
NOAA-EMC/UFS_UTILS pull request #911
Opened 2024-03-08 17:56 UTC by LarissaReames-NOAA

## DESCRIPTION OF CHANGES: 
chgres_cube would produce incorrect surface data or fail with an unhelpful message in debug mode when used with old static data after PR #873 . I added a check in the read of the static fields that looks for any points where landfrac > 0 but static data = -999 (missing data). The program now fails at this point when used with incompatible static data and provides a useful error message directing the user to create new static data with an un-to-date UFS_UTILS build. 

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [ ] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [X ] Compile branch on Hera using GNU.
- [ ] Compile branch in 'Debug' mode on WCOSS2.
- [X ] Run unit tests locally on any Tier 1 machine.
- [ X] Run relevant consistency tests locally on all Tier 1 machine.

Compiles with Intel on Jet and Hera. Compiles in debug mode on Hera. Unit tests and regression tests pass on Hera. Will need assistance with: Debug compile on WCOSS2, Intel compile on Orion, Hercules, WCOSS2.

## DEPENDENCIES:
N/A

## DOCUMENTATION:
N/A

## ISSUE: 
Addresses #906

2024-03-08 18:14 UTC, GeorgeGayno-NOAA commented
And you tested this on your problem case? Can you note that under the 'tests conducted' section.

2024-03-12 12:54 UTC, GeorgeGayno-NOAA requested changes

2024-03-12 12:54 UTC, GeorgeGayno-NOAA commented on sorc/chgres_cube.fd/static_data.F90
I don't think variable `land_frac_target_tile` is used.

2024-03-12 12:54 UTC, GeorgeGayno-NOAA commented on sorc/chgres_cube.fd/static_data.F90
>   use netcdf
I don't think `land_frac_target_grid` is used.

2024-03-12 12:54 UTC, GeorgeGayno-NOAA commented on sorc/chgres_cube.fd/static_data.F90
>   subroutine read_static_file(field, i_target, j_target, tile, &
Add argument `land_frac` to the doxygen.

2024-03-12 18:27 UTC, GeorgeGayno-NOAA commented
@LarissaReames-NOAA - I just have three minor comments. Once you address them I can merge.

2024-03-15 21:44 UTC, LarissaReames-NOAA commented on sorc/chgres_cube.fd/static_data.F90
>   subroutine read_static_file(field, i_target, j_target, tile, &
Done in coming commit.

2024-03-15 21:44 UTC, LarissaReames-NOAA commented on sorc/chgres_cube.fd/static_data.F90
>   use netcdf
Done in coming commit.

2024-03-15 21:45 UTC, LarissaReames-NOAA commented on sorc/chgres_cube.fd/static_data.F90
Removed in coming commit.

2024-03-18 12:05 UTC, GeorgeGayno-NOAA commented
Please merge the latest updates from develop. Then, I will approve and merge.

2024-03-18 14:00 UTC, GeorgeGayno-NOAA commented
Doxygen now builds without error using 5c99fb6.

2024-03-18 16:49 UTC, LarissaReames-NOAA commented
> Doxygen now builds without error using [5c99fb6](https://github.com/ufs-community/UFS_UTILS/commit/5c99fb691a7915d094db715dbde9b92eba98b85f).

Done.

2024-03-19 20:04 UTC, GeorgeGayno-NOAA approved these changes
Looks good. Will merge.

2024-03-19 20:36 UTC, GeorgeGayno-NOAA commented
@LarissaReames-NOAA and @BenjaminBlake-NOAA Is this fix required for RRFSv1? If so, I will need to update the tag: https://github.com/ufs-community/UFS_UTILS/releases/tag/ufs_utils_1_12_2

2024-03-20 12:43 UTC, merged

2024-03-20 14:33 UTC, BenjaminBlake-NOAA commented
@GeorgeGayno-NOAA  Since this issue came about after PR #873 was merged, I don't think so.  The tag for RRFSv1 was created just before the changes associated with 873.