to compile on GCP and Azure
NOAA-EMC/UFS_UTILS pull request #953
Opened 2024-05-28 15:52 UTC by weihuang-jedi

## DESCRIPTION OF CHANGES: 
Enable UFS_UTILS compilation on GCP and Azure.

## TESTS CONDUCTED: 

- [x] Compiled branch on GCP
- [x] Compiled branch on Azure
- [x] Compiled branch on AWS
- [x] Compiled branch at 472bbe1 on Hercules, Hera, Jet and WCOSS2. Did not compile on Orion as that machine was recently upgraded to Rocky 9 and UFS_UTILS has not been ported there yet. 

## DEPENDENCIES:
None

## ISSUE: 
Fixes #952.

2024-06-10 13:45 UTC, GeorgeGayno-NOAA requested changes
Please see my comment about Gaea.

2024-06-10 13:45 UTC, GeorgeGayno-NOAA commented on sorc/machine-setup.sh
>      module purge
These updates are for Gaea? Did you compile on Gaea? I don't have access to that machine, so you will need to check.

2024-06-10 15:14 UTC, weihuang-jedi commented on sorc/machine-setup.sh
>      module purge
George, 
Thanks for pointing out this, I did not write those code, those code somehow got in at the time I tried to sync my branch with develop, and messed up at my end.
I have re-sync with develop, and only added the code needed for cloud machines (AWS, Azure, GCP),
and compiled the new branch on AWS, GCP, and Azure, also compiled on Hera, and Gaea, all compiled fined.
Could please check again?
Thank you,
Wei

2024-06-10 17:39 UTC, GeorgeGayno-NOAA commented on sorc/machine-setup.sh
> +    if [[ ! -v PW_CSP ]]; then
Not sure why you have two warning messages here.

2024-06-10 17:43 UTC, GeorgeGayno-NOAA commented on sorc/machine-setup.sh
> +            module purge
On Hera, I tried to simulate an error on a non-supported, non-cloud platform:

```
 elif [[ -d /lfs/h1 ]] ; then
     target=wcoss2
     module reset
-elif [[ -d /scratch1 ]] ; then
+elif [[ -d /sratch1 ]] ; then
     # We are on NOAA Hera
```

I got two warnings - one for a CSP platform. 

```
++ echo WARNING: UNSUPPORTED CSP PLATFORM
WARNING: UNSUPPORTED CSP PLATFORM
++ echo WARNING: UNKNOWN PLATFORM
WARNING: UNKNOWN PLATFORM
```

2024-06-11 13:03 UTC, GeorgeGayno-NOAA approved these changes

2024-06-14 20:30 UTC, weihuang-jedi commented
@GeorgeGayno-NOAA Do we need more reviewers, or we can merge this PR?
Thanks.

2024-06-17 12:08 UTC, GeorgeGayno-NOAA commented
> @GeorgeGayno-NOAA Do we need more reviewers, or we can merge this PR? Thanks.

Merge the latest updates from 'develop'. Then I will merge this PR.

2024-06-17 14:31 UTC, weihuang-jedi commented
I have sync my branch with "develop". Thanks.


On Mon, Jun 17, 2024 at 6:08 AM GeorgeGayno-NOAA ***@***.***>
wrote:

> @GeorgeGayno-NOAA <https://github.com/GeorgeGayno-NOAA> Do we need more
> reviewers, or we can merge this PR? Thanks.
>
> Merge the latest updates from 'develop'. Then I will merge this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/UFS_UTILS/pull/953#issuecomment-2173228278>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMCH65GP4SRON6O3AMJKJ3ZH3GU3AVCNFSM6AAAAABINHAFSSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZTGIZDQMRXHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-17 20:30 UTC, GeorgeGayno-NOAA approved these changes

2024-06-17 20:31 UTC, GeorgeGayno-NOAA commented
@weihuang-jedi - Thanks. Will merge.

2024-06-18 11:57 UTC, merged

2024-06-18 13:29 UTC, weihuang-jedi commented
Thank you @George Gayno - NOAA Affiliate ***@***.***> !

On Tue, Jun 18, 2024 at 5:58 AM GeorgeGayno-NOAA ***@***.***>
wrote:

> Merged #953 <https://github.com/ufs-community/UFS_UTILS/pull/953> into
> develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/UFS_UTILS/pull/953#event-13200011070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMCH67P4VP5V67QR5C3N5LZIAOELAVCNFSM6AAAAABINHAFSSVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTGIYDAMBRGEYDOMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>