sfc_climo_gen - use scale parameter to read scaled datasets
NOAA-EMC/UFS_UTILS pull request #958
Opened 2024-06-03 13:56 UTC by sanatcumar

## DESCRIPTION OF CHANGES: 
Update `sfc_climo_gen` to use optional scaling parameter to read surface fields when used.

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [ ] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [ ] Compile branch on Hera using GNU.
- [ ] Compile branch in 'Debug' mode on WCOSS2.
- [ ] Run unit tests locally on any Tier 1 machine.
- [ ] Run relevant consistency tests locally on all Tier 1 machines.

Describe any additional tests performed.

## DEPENDENCIES:
Add any links to pending PRs that are required prior to merging this PR. For example:

ufs-community/UFS_UTILS/pull/<pr_number>

## DOCUMENTATION:
If this PR is contributing new capabilities that need to be documented, please also include updates to the RST files in the docs/source directory as supporting material.

## ISSUE: 
Fixes #957.

2024-06-03 18:58 UTC, GeorgeGayno-NOAA commented
@sanatcumar - there should be a list of tests in the description section (automatically added via by this file: https://github.com/ufs-community/UFS_UTILS/blob/develop/.github/PULL_REQUEST_TEMPLATE)

I will add them manually.

2024-06-24 12:16 UTC, GeorgeGayno-NOAA commented
@sanatcumar - what is the status of this PR?

2024-06-24 14:38 UTC, sanatcumar commented
> @sanatcumar - what is the status of this PR?

 Hi George , I was waiting on using this new data sets for some test runs before I do this. I guess now is as good as ever. I see you have added from template. Thanks. I will do some quick checks and request a review soon.

2024-06-27 18:02 UTC, GeorgeGayno-NOAA commented
> > @sanatcumar - what is the status of this PR?
> 
> Hi George , I was waiting on using this new data sets for some test runs before I do this. This also involves adding a new data set to the fix directories. Could you refresh my memory on whom to contact or to raise a new dependency issue ?
> 
> I see you have added from template. Thanks. I will do some quick checks and request a review soon.
> 
> Cheers and thanks again

If you want new 'fixed' data hosted to the official baselines, make your request here (fixed file update): https://github.com/NOAA-EMC/global-workflow/issues/new/choose

2024-08-22 13:18 UTC, GeorgeGayno-NOAA requested changes
Your branch looks out of date. Merge the latest updates from 'develop'.

Also, I see a branch called 'use_scale' in the authoritative fork.  What is that? All branches should be in user forks.

2024-08-22 14:01 UTC, sanatcumar commented
> Your branch looks out of date. Merge the latest updates from 'develop'.
> 
> Also, I see a branch called 'use_scale' in the authoritative fork. What is that? All branches should be in user forks.

Hi George, Just synced to the latest develop and also deleted the branch in the authoritative fork. Thanks for pointing it out .

2024-08-22 18:52 UTC, GeorgeGayno-NOAA commented
@sanatcumar - did you perform any of the tests under "TEST CONDUCTED". If you don't have access to a machine listed, let me know and I can run the tests for you.

2024-08-22 19:02 UTC, sanatcumar commented
> @sanatcumar - did you perform any of the tests under "TEST CONDUCTED". If you don't have access to a machine listed, let me know and I can run the tests for you.

Hi @GeorgeGayno-NOAA , thanks, 
 I can run on Hera and Orion . I do not have access to others. 
I changed my Phone and now my RSA needs to be setup again for access to Orion though. I am working on it.

2024-09-24 19:29 UTC, GeorgeGayno-NOAA commented
@sanatcumar - what is the status of this PR?

2024-09-24 21:47 UTC, sanatcumar commented
> @sanatcumar - what is the status of this PR?

Hi George,
 I am running into  out of memory issues when I ran this on Orion. I tried to set the bigmem option and tried to increase the nodes and decrease the tasks per nodes to no avail.  Do you have any suggestions ?.
Sanath

2024-09-25 16:59 UTC, GeorgeGayno-NOAA commented
> > @sanatcumar - what is the status of this PR?
> 
> Hi George, I am running into out of memory issues when I ran this on Orion. I tried to set the bigmem option and tried to increase the nodes and decrease the tasks per nodes to no avail. Do you have any suggestions ?. Sanath

I would need to see your test script. How big is this new LAI data?

2024-11-05 22:03 UTC, sanatcumar commented
> > > @sanatcumar - what is the status of this PR?
> > 
> > 
> > Hi George, I am running into out of memory issues when I ran this on Orion. I tried to set the bigmem option and tried to increase the nodes and decrease the tasks per nodes to no avail. Do you have any suggestions ?. Sanath
> 
> I would need to see your test script. How big is this new LAI data?

Hi @GeorgeGayno-NOAA, the file size is about **10 Gig**s . If you can see the log file at /home/skumar/UFS_UTILS/driver_scripts/log.fv3_grid_driver

"
 /home/skumar/UFS_UTILS/driver_scripts/../fix/sfc_climo/LAI_climo_pnnl.nc
 - CALL FieldScatter FOR SOURCE GRID DATA.
 - CALL FieldScatter FOR SOURCE GRID DATA.
..........
 - CALL FieldRegridStore.
slurmstepd: error: Detected 1 oom_kill event in StepId=19020013.0. Some of the step tasks have been OOM Killed.
srun: error: orion-25-65: task 0: Out Of Memory
"

I used 
#SBATCH --nodes=6 --ntasks-per-node=12
#SBATCH --partition=bigmem
I tried with reducing the nodes to 2 and ntasks to 6 to no avail

Hope you can help me resolve this.
Cheers and thanks
Sanath

2024-11-06 16:46 UTC, GeorgeGayno-NOAA commented
> > > > @sanatcumar - what is the status of this PR?
> > > 
> > > 
> > > Hi George, I am running into out of memory issues when I ran this on Orion. I tried to set the bigmem option and tried to increase the nodes and decrease the tasks per nodes to no avail. Do you have any suggestions ?. Sanath
> > 
> > 
> > I would need to see your test script. How big is this new LAI data?
> 
> Hi @GeorgeGayno-NOAA, the file size is about **10 Gig**s . If you can see the log file at /home/skumar/UFS_UTILS/driver_scripts/log.fv3_grid_driver
> 
> " /home/skumar/UFS_UTILS/driver_scripts/../fix/sfc_climo/LAI_climo_pnnl.nc
> 
> * CALL FieldScatter FOR SOURCE GRID DATA.
> * CALL FieldScatter FOR SOURCE GRID DATA.
>   ..........
> * CALL FieldRegridStore.
>   slurmstepd: error: Detected 1 oom_kill event in StepId=19020013.0. Some of the step tasks have been OOM Killed.
>   srun: error: orion-25-65: task 0: Out Of Memory
>   "
> 
> I used #SBATCH --nodes=6 --ntasks-per-node=12 #SBATCH --partition=bigmem I tried with reducing the nodes to 2 and ntasks to 6 to no avail
> 
> Hope you can help me resolve this. Cheers and thanks Sanath

You can try increasing the nodes - try 8 nodes and 12 tasks per node. The LAI uses conservative interpolation, which is likely very expensive. If increasing the nodes does not work, you may have to upscale LAI dataset to 0.03 or 0.05-degree as we have done with the soil and vegetation type datasets.  Or you can try a different interpolation method.

Since we are running into these memory issues more frequently, perhaps we should replace `sfc_climo_gen` with a program that does not rely on ESMF. But that is a 'day two' project. ESMF is convenient when interpolating from tiles to tiles. But interpolating from lat/lon to tiles could be done using the NCEPLIBS IPOLATES library.

2025-04-08 16:26 UTC, GeorgeGayno-NOAA commented
@sanatcumar - there has been no movement on this PR for a while. What is the status?

2025-04-14 16:09 UTC, sanatcumar commented
Hi George,
 I was not able to resolve the memory related issue on Orion. It was suggested that I try and use a compression to reduce the size of the Lai file and also to see if a lower resolution Lai file can also be made.  I will check my past email if you had send me some code snippets and suggestions for reducing the  file sizes

2025-08-19 15:14 UTC, GeorgeGayno-NOAA commented
@sanatcumar - any progress on this? This PR has been open for over a year.

2025-08-22 16:41 UTC, GeorgeGayno-NOAA commented
Will close for now. @barlage can decide the future of this task.

2025-08-22 16:42 UTC, closed without merging